import '@/ui/globals.css'
import type { Metadata } from 'next'
import { Analytics } from '@vercel/analytics/react'
import { segoeui } from '@/ui/fonts'

export const metadata: Metadata = {
  title: 'Douglas Nascimento - Site Pessoal',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@24,400,1,0" />
      </head>
      <body className={`${segoeui.className} antialiased`}>
        {children}
        <Analytics/>  
      </body>
    </html>
  )
}
